# IEOR 4703 -- Monte Carlo Simulation for FE

### Generation of multivariate normal random variables

In [1]:
import numpy as np

We generate samples from $X \sim \mathrm{N}(\mu,\Sigma)$ using the Cholesky decomposition. We set $\mu = 0$.

In [2]:
Sig = np.array([[1.0, 0.2, 0.3, 0.4],
               [0.2, 1.5, 0.3, 0.5],
               [0.3, 0.3, 2.0, 0.1],
               [0.4, 0.5, 0.1, 3.0]])

Find $A$ such that $\Sigma = A \times A^\top$.

In [3]:
A = np.linalg.cholesky(Sig)
print(A)

[[ 1.          0.          0.          0.        ]
 [ 0.2         1.2083046   0.          0.        ]
 [ 0.3         0.19862541  1.36767977  0.        ]
 [ 0.4         0.34759447 -0.06510376  1.64770737]]


Generate samples of vectors $Z \sim \mathrm{N}(0,I)$ of size 4.

In [4]:
np.random.seed(34567812)

In [5]:
n = 30000
Z = np.random.randn(4, n)

We check the sample covariance, which should be close to the identity matrix.

In [6]:
np.round(np.cov(Z),4)

array([[ 1.004 ,  0.0022,  0.0062, -0.0031],
       [ 0.0022,  1.0144, -0.0035, -0.0067],
       [ 0.0062, -0.0035,  1.0167, -0.003 ],
       [-0.0031, -0.0067, -0.003 ,  1.002 ]])

We compute $X = A \times Z$, which has the desired distribution.

In [7]:
X = np.dot(A, Z)

As a sanity check, we compute the sample covariance, which should be close to $\Sigma$.

In [8]:
np.round(np.cov(X),4)

array([[1.004 , 0.2035, 0.31  , 0.3969],
       [0.2035, 1.5222, 0.3004, 0.4935],
       [0.31  , 0.3004, 2.0356, 0.0916],
       [0.3969, 0.4935, 0.0916, 2.9972]])

In [9]:
Sig

array([[1. , 0.2, 0.3, 0.4],
       [0.2, 1.5, 0.3, 0.5],
       [0.3, 0.3, 2. , 0.1],
       [0.4, 0.5, 0.1, 3. ]])